(define (domain table-tamp)
    (:requirements :strips :equality)
    (:predicates
        (Conf ?q)
        (AtConf ?q)
        (ObjPose ?o ?p)
        (AtPose ?o ?p)
        (Grasp ?o ?g)
        (GraspSet ?g1 ?g2)
        (On ?o ?r)
        (Kin ?o ?p ?q ?g)
        (Holding ?o)
        (HandEmpty)
        (Graspable ?o)
        (Trajectory ?q1 ?q2 ?t)
        (Traj ?t)
        (UnSafeTraj ?t)
        (CFree ?t ?o ?g)
        (Trajectory_Holding ?o ?g ?q1 ?q2 ?t)
        (Traj_Holding ?t ?o ?g)
        (UnSafeHolding ?t ?o ?g)
        (CFreeHolding ?t ?o ?g ?o2 ?p)
        (Region ?r)
        (Supported ?o ?p ?r)
        (AtGrasp ?o ?g)
        (InCollision ?o ?p)
        (Safe ?o ?p ?o2 ?p2)

    )

    (:action move_free
        :parameters (?q1 ?q2 ?t)
        :precondition (and (Trajectory ?q1 ?q2 ?t)
                            (Conf ?q1)
                            (Conf ?q2)
                            (AtConf ?q1)
                            (HandEmpty)
                            ;(not (UnSafeTraj ?t))
                            )
        :effect (and (AtConf ?q2) (not (AtConf ?q1)))
    )

    (:action move_holding
        :parameters (?o ?g ?q1 ?q2 ?t)
        :precondition (and (Trajectory_Holding ?o ?g ?q1 ?q2 ?t)
                            (Conf ?q1)
                            (Conf ?q2)
                            (AtConf ?q1)
                            (Holding ?o)
                            (AtGrasp ?o ?g)
                            ;(not (UnSafeHolding ?t ?o ?g))
                            )
        :effect (and (AtConf ?q2) (not (AtConf ?q1)))
    )

    (:action grab
        :parameters (?o ?p ?q ?g1 ?g2)
        ;:parameters (?o ?p ?q ?g)
        :precondition (and (HandEmpty)
                          (AtConf ?q)
                          (Kin ?o ?p ?q ?g1)
                          (AtPose ?o ?p)
                          (Grasp ?o ?g1)
                          (Grasp ?o ?g2)
                          (Graspable ?o)
                          (GraspSet ?g1 ?g2)
                          )
        :effect (and (Holding ?o) (not (HandEmpty)) (not (AtPose ?o ?p)) (AtGrasp ?o ?g2))
    )

    (:action place
        :parameters (?o ?p ?q ?g)
        :precondition (and (not (HandEmpty))
                          (ObjPose ?o ?p)
                          (AtConf ?q)
                          (Kin ?o ?p ?q ?g)
                          (Holding ?o)
                          (AtGrasp ?o ?g)
                          (not (InCollision ?o ?p))
                          )
        :effect (and (not (Holding ?o)) (HandEmpty) (AtPose ?o ?p) (not (AtGrasp ?o ?g)))
    )

    (:derived (On ?o ?r)
        (exists (?p) (and (Region ?r) (AtPose ?o ?p) (Supported ?o ?p ?r)))
    )

    (:derived (InCollision ?o ?p)
        (exists (?o2 ?p2) (and (AtPose ?o2 ?p2) (not (Safe ?o ?p ?o2 ?p2))))
    )

    (:derived (UnSafeTraj ?t)
        (exists (?o ?p) (and (AtPose ?o ?p) (not (CFree ?t ?o ?p))))
    )

    (:derived (UnSafeHolding ?t ?o ?g)
        (exists (?o2 ?p) (and (AtGrasp ?o ?g) (AtPose ?o ?p) (not (CFreeHolding ?t ?o ?g ?o2 ?p))))
    )
)
